### ISSUE TITLE
Bug: Impossible to map DPad axis buttons

### ISSUE THREAD

**Issue by ShadowApex** [ShadowBlip/InputPlumber#151]
In some gamepad implementations, the dpad is defined as a 2-axis input instead of individual button inputs, which makes the axis dpad impossible to map. This created two divergent capabilities:

* `Gamepad:Axis:Buttons`
* `Gamepad:Button:Dpad[Up,Down,Left,Right]`

We should consolidate these two implementations into just `Gamepad:Button:Dpad[x]`.

**Comment by pastaq** [comment]
I'd like to include a fix for this in #149
