### ISSUE TITLE
Feature: To become a gui application similar to steam input.

### ISSUE THREAD

**Issue by defiling9046** [ShadowBlip/InputPlumber#201]
A gui application (similar to how steaminput works) would be great for non advanced users and just general users.

**Comment by pastaq** [comment]
OpenGamepadUI is used as a GUI front end for InputPlumber. We don't currently have plans for a standalone desktop application. If someone else wants to take on that project I'd be more than willing to provide some assistance, but we're around the maximum for the number of projects we can effectively maintain ourselves.
