### ISSUE TITLE
Issues switching to DS5 or DS5 Edge driver on Nov 5 Steam client

### ISSUE THREAD

**Issue by uejji** [ShadowBlip/InputPlumber#226]
Steam client shows no controllers detected when switching InputPlumber to ds5 or ds5-edge driver until the Steam client is reset, whether through busctl call or editing the device file and restarting IP.  This behavior isn't observed when switching to xb360, xbox-series, xbox-elite or deck drivers via either method.

I went back to a 2 month old installation of SteamFork and the issue reappeared once the Steam client updated.

**Comment by pastaq** [comment]
Is this resolved in the latest steam client?

**Comment by uejji** [comment]
It looks like it is.  I'll mark this resolved.

**Comment by uejji** [comment]
Fixed in the latest stable Steam client.
