### ISSUE TITLE
Issue: After wakeup from sleep 3 inputPlumber devices are shown on the Neo

### ISSUE THREAD

**Issue by philmmanjaro** [ShadowBlip/InputPlumber#40]
When you put the OrangePi Neo to sleep and wake it up a while after LC and RC act differently. Also I noticed to have 3 inputPlumber devices visible. Only when I stop and restart the systemd service on inputPlumber device is shown in SteamUI and all buttons work with default settings again.

**Comment by pastaq** [comment]
I was not able to reproduce this issue with the DualSense Edge target device on the Legion Go, ROG Ally, or AYANEO Flip. Can you confirm this issue in the latest version?
